const INCREMENT = 'LONG_PREFIX_INCREMENT' as const
const DECREMENT = 'LONG_PREFIX_DECREMENT' as const
const SET_COUNT = 'LONG_PREFIX_SET_COUNT' as const

export default {
  INCREMENT,
  DECREMENT,
  SET_COUNT
};
